### ISSUE TITLE
Continue whole anime download even if one episode is not working

### ISSUE THREAD

**Issue by wolferave** [phoenixthrush/AniWorld-Downloader#19]
Hey phoenixrush,
just discovered your program and feel like I found the holy grail. Thanks a lot for your work!!

I have a small issue with downloading a whole season or even the whole anime. I tried to download a anime with a lot of episodes over night and discovered this morning that it stop in middle of the night due to one episode link was not working. 
Is there an option to continue with the next episode for a whole season/anime download? I think this might be very helpful.

**Comment by phoenixthrush** [comment]
Hey wolferave,  
thanks for the kind words!  

By the way, have you used the episode file for downloading?

This actually gave me an idea for a new feature—adding an optional argument to have the PC shut down automatically after finishing. I could also set it up to create a log.txt file with timestamps, showing if any episodes or even entire series were skipped.

It should normally continue to the next episode automatically instead of stopping or crashing. I'll check it out.

**Comment by phoenixthrush** [comment]
Could you tell me one of the animes where this error happened so I can test it out?

**Comment by Tmaster055** [comment]
Hi Wolferave!

AniWorld-Downloader thinks One Piece Season 2 has 17 episodes instead of 16, which is causing it to crash. So far, One Piece is the only anime with this issue we know.

If you like our project, please consider giving it a star on GitHub. Thanks for the support!😁

**Comment by phoenixthrush** [comment]
Hi, could you please let me know if this problem is still happening?
