### ISSUE TITLE
How to download from streamkiste.tv

### ISSUE THREAD

**Issue by YozouChan** [phoenixthrush/AniWorld-Downloader#32]
Hello,
this might be a stupid question of mine, but i don't really understand how to download from streamkiste.tv.
In the table of Supported Sites and Extractors is streamkiste.tv listed with "Native extractor", but i don't know what it means. ;-;

Could someone give me an example command of how i download something from streamkiste, please?
I tried 'aniworld --episode <streamkiste.tv link>' but that doesn't worked.

Thank you in advance! <3

**Comment by YozouChan** [comment]
Hello again,
i have another question. How do i download the special episodes on AniWorld via command?
Because it's not a season or anything and i couldn't find it in the README
![image](https://github.com/user-attachments/assets/459ec738-04a9-4cba-928d-27284ba1b822)

Thank you in advance <3
(and i apologize for my incompetence)

**Comment by phoenixthrush** [comment]
Hi, this doesn't sound stupid at all as we haven't given even one example about this in README yet. 

Yeah "Native Extractor" might be stupid phrased, it just means that there is something written specifically to be used on this site which only works for this site.

You can see all the "native" extractors in src/aniworld/extractors and inside one of the folders like streamkiste/ there are the appropriate files which can be run completely independently of aniworld directly as it should not depend on anything else than the file itself (I just checked, it uses the voe extractor from aniworld but as long as aniworld is installed, it should work anyways :) ). After running it manually using the complete path of the file it will ask you about the link to the site or what todo. 'aniworld --episode <streamkiste.tv link>', should have worked too but maybe it's better to run the file directly (because values like Watch and Download and others aren't passed) or changing the headless variable in code from False to True (line 52, I just checked its already False) to see whats going on, maybe it ran and failed because of a captcha or something like this, I haven't tested it a while and the site could have changed up maybe, if so I'll rewrite it again.

Special episodes are movies on aniworld and can be downloaded by using the menu by scrolling down there will be a movie section, I don't know if --episode <link-with-last-season-episode> --keep-watching will work as it should generate the movies but there indeed is no option to specify the movie link as --episode. I'll do this all in the next branch instead which is almost working as fine.

Don't feel like this you aren't wrong if something is unclear it's not because of the user it's because of bad documentation.

Also sorry for the unusual late response as I am on vacation for some weeks and the time shift is really bad (GMT+7) and will be even worse (GMT+9) from German time lol.

**Comment by phoenixthrush** [comment]
"I don't know if --episode --keep-watching will work"

I meant using --episode with the last episode of the last season and then appending --keep-watching.

But still, I haven't tested if it works, it's just a guess.

**Comment by YozouChan** [comment]
Alright, Thank you pretty much <3
I'll test it later :D

**Comment by phoenixthrush** [comment]
Just tested, it seems to work. :)
